### ISSUE TITLE
Can't get markdown to work on View page using taghelper

### ISSUE THREAD

**Issue by dotnetshadow** [RickStrahl/Westwind.AspNetCore.Markdown#1]
Greate Library,
For some reason I can't seem to get the taghelper working on an View page that uses the conventional Controller/View. If I use Razor Pages then it works correctly. Even your markdown/markdownpage sample doesn't seem to be working?
```
@{
    ViewData["Title"] = "Index";
}
<h2>Index</h2>
<markdown>    
    #### Changes
</markdown>
```
**UPDATE** It seams I had to add @addTagHelper *, Westwind.AspNetCore.Markdown on the actual viewpage itself even though I specified it in the _viewimports
```
@using SampleWeb
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Westwind.AspNetCore.Markdown
```

**UPDATE2** Using asp.net core 2.2 I get the following error:
```
NullReferenceException: Object reference not set to an instance of an object.

    Westwind.AspNetCore.Markdown.MarkdownTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
    Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)
    AspNetCore.Views_Home_Privacy.ExecuteAsync() in Privacy.cshtml

    <p>@System.Diagnostics.Process.GetCurrentProcess().ProcessName</p>

Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
```
**UPDATE 3** Seems I have to add the middleware for it to work, I assumed I didn't need it

**Comment by RickStrahl** [comment]
The middleware always has to be added (ie. `app.UseMarkdown()` in in `Configure()` as that's what configures the Markdown Parser. Without that the parser is not there. This is a recent change (yesterday) as part of the replacable parser logic. Probably should make it so a default is always set even if UseMarkdown is not run. Fixing now.

The docs need fixing since the config has been pushed down the page a bit.

**Comment by RickStrahl** [comment]
Ok so I've made a number of changes and now the tag helper and Markdown static class methods don't require configuration - they work with just default settings **except for parsing a file** (`Markdown.ParseFromFile()` or TagHelper `file=` attribute) which require access to the HttpContext that has to be injected and which happens as part of `app.ConfigureServices()`.

Give another try with v3.2 and later...

However, recommendation is to add at minimum:


```cs
public void ConfigureServices(IServiceCollection services)
{
	app.AddMarkdown();
}

public void Configure(IApplicationBuilder app)
{
	app.UseMarkdown();
}
```

which has been prominently added to the docs at the top.

**Comment by dotnetshadow** [comment]
Appreciate your prompt efforts.
Cheers I'll definitely have a go at this and report back if I have any issues.
