### ISSUE TITLE
Only for Markdown parsing?

### ISSUE THREAD

**Issue by codeease1** [RickStrahl/Westwind.AspNetCore.Markdown#15]
Hi,

I am a Github newbie, dont know if I can post my questions here?

I see the Westwind website (eg:[ this page](https://weblog.west-wind.com/posts/2018/Apr/18/Creating-a-generic-Markdown-Page-Handler-using-ASPNET-Core-Middleware)), looks like directly parsing markdown file is also a good solution for a website without database (I tried several static site generators like Hugo, Wyam,  but it is not easy to find enough sample pipleline scripts to generate content to integrate with an ASP.NET core project). My question is whether Westwind.AspNetCore.Markdown can also help to generate Related Posts and Tag links (either in the single post and in the home page side bar, just like the feature in a WordPress blog site)?

Thanks!

**Comment by RickStrahl** [comment]
Not really sure what you're asking.

This library only provides Markdown parsing features, nothing else. Any logic related to managing your blog or other 'code' logic isn't really in the domain of this.

The West Wind Weblog - well, that's still running WebForms... :smile: I started in on a Core version with content directly from Github which is interesting, but it's on my long list of things to do.
