### ISSUE TITLE
Title extraction misses a case

### ISSUE THREAD

**Issue by AndyEdmonds** [RickStrahl/Westwind.AspNetCore.Markdown#2]
Hi Rick,
Very well done, and thanks for your work. Currently you get the Title for the Model from the first # tag in the md file. There's another style of markdown - as used in Wikipedia, where the main tag has "=====" underneath.  Could you extract this in preference to the first # tag, i.e. YAML, then "====" then # ?

**Comment by RickStrahl** [comment]
Hmmm... yeah that should be a handled case. I think the preference will be Yaml, # then === as # is the more modern syntax that's most commonly used.

**Comment by RickStrahl** [comment]
Ok, I've added that logic to handle double underlined headers.

Logic is:

* Yaml header Title first
* Then # header 
* Then ====  underlined text header

The headers have to show in the first 10 lines of the document.

Addressed in: c2aa21890b70556f8011517a35c4d975cb766ea4
