### ISSUE TITLE
Images path translation seems to not work

### ISSUE THREAD

**Issue by it-xtech-dev** [RickStrahl/Westwind.AspNetCore.Markdown#20]
Hello,

First to say: This project is awesome! Thanks for great work!

**The problem:**
I would like to render md files with usage of helper inside my view. File content is rendered fine but external links do not work properly (for example images are not displayed). As far as i understand relative links should be by default converted according to current document path - but they seems not to.

**Here is my config:**

Startup.cs

```
        public void ConfigureServices(IServiceCollection services)
        {
            ...
            // add markdown (.md) support.
            services.AddMarkdown();
            ...
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            ...
            // enable markdown (.md) middleware
            app.UseMarkdown();
            ...
        }
```

Docs.cshtml

```
@page
@model MyApp.Pages.DocsModel
@using Westwind.AspNetCore.Markdown

@{ 
    ViewData["Title"] = "Docs";
}
<div class="container" style="background-color: #FFF;padding-top: 1rem;">
    <div class="row">
        <div class="col-12">
            <markdown filename="~/docs/test.md" url-fixup-baseurl="true"></markdown>
        </div>
    </div>
</div>
```

wwwroot/docs/test.md

```
Wygląd przykładowego formularza w aplikacji:
![2020-04-20_21h33_46.png](/.attachments/2020-04-20_21h33_46-4d06419c-e9fd-4dfa-a163-130c5c3f4fa7.png)

```
wwwroot/*
![wwwroot listing](https://i.imgur.com/diDiLeY.png)

Rendered page view:
![render result](https://i.imgur.com/HAzDEfL.png)

Rendered page output html (fragment):
```
<div class="page-content">
            <!---->
            <nav aria-label="breadcrumb" class="breadcrumbs-bar"><ol class="breadcrumb"></ol></nav>
            
<div class="container" style="background-color: #FFF;padding-top: 1rem;">
    <div class="row">
        <div class="col-12">
            <p>Wygląd przykładowego formularza w aplikacji:
<img src="/.attachments/2020-04-20_21h33_46-4d06419c-e9fd-4dfa-a163-130c5c3f4fa7.png" alt="2020-04-20_21h33_46.png"></p>

        </div>
    </div>
</div>
</div>
```

**Comment by RickStrahl** [comment]
Sorry I missed this issue.

Not sure because you're not actually posting your markdown text. Your image path in that case should likely be `![](.attachments/image.png). But probably better would be `/docs/attachments/image.png` for the image link. The parser will not fix up virtual links for content.
