### ISSUE TITLE
Blazor

### ISSUE THREAD

**Issue by EasyLOB** [RickStrahl/Westwind.AspNetCore.Markdown#28]
Hi,

Congratulations, you created a really nice Library :smile:
I am looking for a library to create Help pages and Markdown is really powerfull to create Help/Wiki files.

But I have a question...
Does it work with Blazor Server and Blazor Web Assembly ?
As far as I saw from your code, the answer is NO: correct ?

Thanks

**Comment by twentytwokhz** [comment]
I have the exact same question.. because on my end it does not seem to render the Markdown syntax when using Blazor server

Edit: My mistake, I did not read the specifications carefully. This package is specifically for AspNetCore **NOT** for Blazor

**Comment by EasyLOB** [comment]
Hi,
I solved my problem with [https://github.com/xoofx/markdig](Markdig).
It works with ASP.NET Core MVC, Blazor Server and Blazor Web Assembly.
You have to create your own components, but it's really easy :smile:

**Comment by RickStrahl** [comment]
This library is meant for ASP.NET Core server applications as it provides specific feature for the ASP.NET Core framework for integration into pages and views and managing site content.

For simple integrations that just need Markdown conversion there's no need to use  this library, but using Markdig directly is the recommended approach (or creating a wrapper that provides specific extra functionality similar to what this library provides).
