### ISSUE TITLE
Redirect to Azure login causes error

### ISSUE THREAD

**Issue by soerendalbydk** [RickStrahl/Westwind.AspNetCore.Markdown#29]
When a markdown file is the first file to load for the user, it triggers a redirect to Azure login which in turn causes page info to get lost. The result is an exception _This controller is not accessible directly unless the Markdown Model is set_.

Is it possible to setup that looking up md files should Allow Anonymous? I am using .NET 6 ASP.NET MVC

**Comment by RickStrahl** [comment]
That's a site configuration issue where you auth is kicking in. Not sure how that fixes as that's application specific.
