### ISSUE TITLE
Custom class in tag helper

### ISSUE THREAD

**Issue by MichalSznajder** [RickStrahl/Westwind.AspNetCore.Markdown#31]
Is there a way to append CSS class with "container" to result of tag helper rendering? Something like 
```
<markdown class="prose">
Some text.

Some text.
</markdown>
```
This would render as 
```
<article class="prose">
<p> ... </p>
<p> ... </p>
</div>
```

I know that I can always add container myself but it seems awkward to me to do it every time I need render something.

Maybe for backward compatibility container would be added only if class is specified?

**Comment by RickStrahl** [comment]
No but you can embed a `<div>` tag inside of the container.
