### ISSUE TITLE
Not sure what to do with this warning from VSCodium

### ISSUE THREAD

**Issue by Amondale** [RickStrahl/Westwind.AspNetCore.Markdown#37]
I am using .NET 8 and have added the Markdown.dll to my project. Upon launching a debug session, I see the following in the Debug Console Tab:

`You are debugging a Release build of Westwind.AspNetCore.Markdown.dll. Using Just My Code with Release builds using compiler optimizations results in a degraded debugging experience (e.g. breakpoints will not be hit).`

Help a .NET noob out?

**Comment by RickStrahl** [comment]
Not sure why this comes up, but all that means you can't debug into the code as it's compiled as Release mode.
