### ISSUE TITLE
Respect newlines in string

### ISSUE THREAD

**Issue by halomakes** [RickStrahl/Westwind.AspNetCore.Markdown#4]
I'm using the tag helper and binding the markdown property to a string that has ```\n``` newlines.  The line breaks weren't appearing.  I worked around it by doing a regex replace of line breaks in the string with ```<br/>``` but it'd be nice if that could be taken care of automatically

**Comment by RickStrahl** [comment]
You closed this but just to clarify Markdown's escape options for soft line breaks are:

* Two spaces at the end of the line
* A backslash at the end of the line `\`
* `<br \>` anywhere after the line before the next line
