### ISSUE TITLE
Please remove MarkdownPageProcessor

### ISSUE THREAD

**Issue by imclint21** [RickStrahl/Westwind.AspNetCore.Markdown#8]
Hi,

I create a swagger and I see MarkdownPageProcessor, can you disable it ?

or maybe use `[ApiExplorerSettings(IgnoreApi = true)]`

Thank you

**Comment by RickStrahl** [comment]
It's not going to be removed as it's needed for the page processing pipeline. The attribute I have to check based on what dependencies that pulls in - wouldn't want to have a dependency on the API explorer in this package either.

**Comment by RickStrahl** [comment]
Ok turns out that the attribute can be added without further dependencies. da1fb4a49ee334311aedab209a7030b7db8f5fef

Thank you.

**Comment by imclint21** [comment]
Nice, I will throw an issue for swashbuckle swagger, I think they need to make a system that don't all by default

**Comment by RickStrahl** [comment]
Yeah a way to add an exclusion at the application level would definitely help, since you can't always control what's coming in from dependencies.

Nice catch though - you'd never want the Markdown API to be exposed in Swagger.

**Comment by imclint21** [comment]
Yeah if you make a swagger you don't want see markdownparser as endpoint xd

**Comment by imclint21** [comment]
Interesting https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md#omit-actions-by-convention
